#!/usr/bin/env bash
# Script to install HAproxy
sudo apt update
sudo apt install -y haproxy
echo "
   frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back
backend http_back
   balance roundrobin
   server 33046-web-01 100.27.49.143:80 check
   server 33046-web-02 34.201.161.99:80 check" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy reload
